-- Estructura de Base de Datos para Abarrotes Miguel en Supabase

-- 1. Crear tabla de usuarios
CREATE TABLE users (
  username TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'cajero'))
);

-- 2. Crear tabla de productos
CREATE TABLE products (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  supplier_price NUMERIC DEFAULT 0,
  profit_margin NUMERIC DEFAULT 0,
  price NUMERIC NOT NULL,
  stock INTEGER NOT NULL
);

-- 3. Crear tabla de ventas
CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total NUMERIC NOT NULL,
  cashier TEXT NOT NULL
);

-- 4. Crear tabla de items de venta
CREATE TABLE sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES sales(id) ON DELETE CASCADE,
  product_code TEXT,
  quantity INTEGER NOT NULL,
  price NUMERIC NOT NULL
);

-- Insertar usuario administrador inicial e indestructible
INSERT INTO users (username, password, role) VALUES ('admin', 'admin', 'admin') ON CONFLICT DO NOTHING;

-- Insertar un usuario cajero de prueba
INSERT INTO users (username, password, role) VALUES ('cajero', '1234', 'cajero') ON CONFLICT DO NOTHING;

-- Insertar productos de prueba
INSERT INTO products (code, name, price, stock) VALUES 
('75010001', 'Refresco Cola 600ml', 18.50, 24),
('75010002', 'Papas Sal 170g', 22.00, 15),
('75010003', 'Galletas Chocolate', 15.00, 30)
ON CONFLICT DO NOTHING;
